apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  labels:
    app: order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: dextre78/order-api:latest
        # 'Always' K8s jale la imagen de Docker Hub
        imagePullPolicy: Always 
        ports:
        - containerPort: 8080
        env:  
        - name: Kafka__BootstrapServers
          value: "kafka-service:9092"      
        - name: ConnectionStrings__DefaultConnection          
          value: "Host=postgres;Port=5432;Database=catalogs;Username=appuser;Password=secret"
---
apiVersion: v1
kind: Service
metadata:
  name: order-api-service
spec:
  selector:
    app: order-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  
  type: NodePort